name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to your default branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install .NET SDK 7.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'

      - name: Install .NET SDK 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Bryjen.MudMarkdownEditor.Sample

      - name: Build Blazor WASM app
        run: dotnet publish Bryjen.MudMarkdownEditor.Sample -c Release -o build_output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_output/wwwroot
